apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume2
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
   storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: mnt/data/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
    tier: database
spec:
   storageClassName: manual
   accessModes:
     - ReadWriteOnce
   resources:
    requests:
     storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app
  labels:
    app: postgres-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-app
  template:
     metadata:
      labels:
        app: postgres-app
     spec:
       containers:
        - name: postgres-app
          image: postgres:latest
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: customer-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                 secretKeyRef:
                   key: password
                   name: customer-secret
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: db-name
                  name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data2
       volumes:
        - name: postgres-data2
          persistentVolumeClaim:
            claimName: postgres-volume-claim
       restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres-app
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30012
  type: NodePort